language: node_js
node_js: lts/*
os: osx
osx_image: xcode9.4
env:
  global:
    - APP_NAME=War3Keys
    - CSC_IDENTITY_AUTO_DISCOVERY=false
before_install:
  - brew update
install:
  - yarn install
before_script:
  - sudo Xvfb :99 -ac -screen 0 1920x1080x8 &
script:
  - yarn test --coverage
  - yarn dist
